GET http://localhost:3000/api/books HTTP/1.1

###
POST http://localhost:3000/api/books/invalidId HTTP/1.1
Content-Type: application/json

{
    "comment": "test"
}

###npm

DELETE http://localhost:3000/api/books/647e92a2f94097110459d571  HTTP/1.1
Content-Type: application/json

###

DELETE  http://localhost:3000/api/books HTTP/1.1
